# action.yml
name: "Cloudsmith Push"
description: "Push packages easily to your repositories"
author: "Cloudsmith Ltd"
branding:
  icon: "box"
  color: "blue"
inputs:
  api-version:
    description: "All: If provided, a specific version of the Cloudsmith API is installed/used."
    required: false
    default: none
  cli-version:
    description: "All: If provided, a specific version of the Cloudsmith CLI is installed/used."
    required: false
    default: none
  skip-install-cli:
    description: "All: If true, the Cloudsmith CLI will not be installed."
    required: false
    default: "false"
  api-key:
    description: "All: The Cloudsmith API Key (can be provided via GitHub secrets), or set as the CLOUDSMITH_API_KEY environment variable."
    required: false
    default: none
  command:
    description: "All: The desired action with cloudsmith (push, list, etc)."
    required: false
    default: "push"
  format:
    description: "All: The format (deb, npm, maven, etc) for the package."
    required: true
    default: none
  owner:
    description: "All: The user/organization that owns the repository, where the package will be pushed to."
    required: true
    default: none
  repo:
    description: "All: The repository slug (textual identifier), where the package will be pushed to."
    required: true
    default: none
  file:
    description: "All: The primary file for the package (e.g. my-package.deb)."
    required: true
    default: none
  republish:
    description: "All: If true, the uploaded package will overwrite any others with the same attributes."
    required: false
    default: "false"
  wait-interval:
    description: "All: The time in seconds to between checking synchronization."
    required: false
    default: none
  no-wait-for-sync:
    description: "All: If true, don't wait for package synchronization to complete before exiting (faster uploads)."
    required: false
    default: "false"
  extra:
    description: "All: Extra arguments passed to the Cloudsmith CLI, in-verbatim."
    required: false
    default: none
  distro:
    description: "Alpine/Debian/RedHat: The distribution for the package (e.g. ubuntu)"
    required: false
    default: none
  release:
    description: "Alpine/Debian/RedHat: The named version of the release for the package (e.g. xenial)"
    required: false
    default: none
  name:
    description: "Raw: The name for the package."
    required: false
    default: none
  summary:
    description: "Raw: The one-liner synopsis for the package."
    required: false
    default: none
  description:
    description: "Raw: The longer textual description for the package."
    required: false
    default: none
  version:
    description: "Raw: The version for the package."
    required: false
    default: none
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - -a${{ inputs.api-version }}
    - -c${{ inputs.cli-version }}
    - -C${{ inputs.skip-install-cli }}
    - -k${{ inputs.api-key }}
    - -K${{ inputs.command }}
    - -f${{ inputs.format }}
    - -o${{ inputs.owner }}
    - -r${{ inputs.repo }}
    - -F${{ inputs.file }}
    - -P${{ inputs.republish }}
    - -w${{ inputs.wait-interval }}
    - -W${{ inputs.no-wait-for-sync }}
    - -d${{ inputs.distro }}
    - -R${{ inputs.release }}
    - -n${{ inputs.name }}
    - -s${{ inputs.summary }}
    - -S${{ inputs.description }}
    - -V${{ inputs.version }}
    - " -- ${{ inputs.extra }}"
