name: Generate Executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install shiv
        run: pip install shiv

      - name: Generate Executable
        run: shiv -c cloudsmith -o ./cloudsmith cloudsmith-cli

      - name: Commit and push if it's updated
        run: |
          git config --local user.email "bblizniak@cloudsmith.io"
          git config --local user.name "bblizniak"
          git add cloudsmith
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update executable"; git push)