name: Push Dart

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    name: Dart Push Demo
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Push
        id: push
        uses: ./
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "dart"
          owner: "cloudsmith"
          repo: "actions"
          republish: "true" # needed ONLY if version is not changing
          file: "test/fixture/cloudsmith-dart-example-1.0.0.tar.gz" #real file that will repeat versions
