name: Push Debian

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    name: Debian Push Demo
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Push
        id: push
        uses: ./
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "cloudsmith"
          repo: "actions"
          distro: "ubuntu"
          release: "xenial"
          republish: "true" # needed ONLY if version is not changing
          file: "test/fixture/cloudsmith-debian-example-1.0.0-amd64.deb" #real file that will repeat versions
