name: Push Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    name: Docker Push Demo
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Push
        id: push
        uses: ./
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "docker"
          owner: "cloudsmith"
          repo: "actions"
          republish: "true" # needed ONLY if version is not changing
          file: "test/fixture/cloudsmith-docker-example-1.0.0.tar.gz" #alpine image saved to file
